/**
 * FILE: LearningPlanPage.tsx
 * LOCATION: src/components/learning/LearningPlanPage.tsx
 * PURPOSE: Reusable, production-quality detail-page renderer for class subjects
 *          and engineering language/skill plans. Dynamic route files provide the
 *          plan data; this component renders a complete and professional page
 *          with: hero section, chapter/module list, day count badges, difficulty
 *          indicators, start CTA, stats sidebar, and study tips.
 *          Every page generated by this component looks polished and complete —
 *          no placeholder or "coming soon" states.
 * USED BY: src/app/class-9/[subject]/page.tsx, class-10, class-11, class-12,
 *          src/app/engineering/[slug]/page.tsx
 * DEPENDENCIES: lucide-react, next/link, LearningPlanPage.module.css
 * LAST UPDATED: 2026-05-16
 * AUTHOR NOTE: The accent color is passed per-plan so each subject has its own
 *              brand color. Apply it via CSS custom properties on the section element.
 */

import Link from "next/link";
import {
  ArrowLeft, ArrowRight, BookOpen, CheckCircle2,
  Clock, Target, Flame, Trophy, Zap, Calendar,
  ChevronRight, Star, TrendingUp, Users, Brain,
} from "lucide-react";
import type { LearningPlan } from "@/lib/curriculum/learning-catalog";
import styles from "./LearningPlanPage.module.css";

/* ─────────────────────────────────────────────
 * Types
 * ───────────────────────────────────────────── */

interface LearningPlanPageProps {
  /** The curriculum plan data passed from the dynamic route */
  plan: LearningPlan;
}

/* ─────────────────────────────────────────────
 * Study Tips per subject type
 * ───────────────────────────────────────────── */

/**
 * Returns a set of 3 study tips relevant to the plan's subject area.
 * These are shown in the sidebar to guide the student's learning approach.
 */
function getStudyTips(plan: LearningPlan): string[] {
  const title = plan.title.toLowerCase();

  if (title.includes("math")) {
    return [
      "Solve at least 5 practice problems per day — don't just read the theory",
      "Write out all steps even for simple problems to build exam habits",
      "Attempt the hard questions without hints first — then check the explanation",
    ];
  }
  if (title.includes("science") || title.includes("chemistry") || title.includes("physics") || title.includes("biology")) {
    return [
      "Draw diagrams from memory after reading each chapter — it forces recall",
      "Focus on understanding the 'why' behind each concept, not just the 'what'",
      "Review previous chapters' questions every 3 days to prevent forgetting",
    ];
  }
  if (title.includes("english")) {
    return [
      "Read each passage aloud once before answering comprehension questions",
      "Maintain a vocabulary notebook — add 5 new words per session",
      "Practice essay writing with a timer to build exam writing speed",
    ];
  }
  if (title.includes("python") || title.includes("java") || title.includes("c++") || title.includes("code")) {
    return [
      "Type every code example yourself — never copy-paste while learning",
      "After reading a concept, close the book and try to code it from scratch",
      "Debug your own errors before looking for solutions — it builds real skill",
    ];
  }
  /* Default tips for social science, hindi, history, etc. */
  return [
    "Create a one-page summary for each chapter after you finish studying it",
    "Practice writing 5-mark and 10-mark answers with a 10-minute time limit",
    "Use dates, names, and key terms as anchor points for memory — not full paragraphs",
  ];
}

/* ─────────────────────────────────────────────
 * Main Component
 * ───────────────────────────────────────────── */

/**
 * LearningPlanPage — renders a complete learning plan detail page.
 *
 * Structure:
 *   - Back link → hero section → 2-column grid
 *   - Left column: chapter/module list (numbered, with day count)
 *   - Right sidebar: sticky CTA card + stats + study tips
 */
export default function LearningPlanPage({ plan }: LearningPlanPageProps) {
  /* Total study days (already computed in the catalog) */
  const totalDays = plan.durationDays;

  /* Approximate number of questions (15 per chapter on average) */
  const estimatedQuestions = plan.chapters.length * 15;

  /* Study tips tailored to the subject */
  const studyTips = getStudyTips(plan);

  /* XP points the student will earn by completing this plan */
  const estimatedXp = plan.chapters.length * 100 + totalDays * 50;

  return (
    <div className={styles.page}>

      {/* ── Back Navigation ── */}
      <Link href={plan.backHref} className={styles.backLink}>
        <ArrowLeft size={15} />
        Back to {plan.eyebrow}
      </Link>

      {/* ── Hero Section ── */}
      <section className={styles.hero} style={{ borderTopColor: plan.accent }}>
        <div className={styles.heroInner}>
          <div>
            {/* Subject eyebrow e.g. "Class 9" or "Engineering" */}
            <span className={styles.eyebrow} style={{ color: plan.accent }}>
              {plan.eyebrow}
            </span>
            <h1 className={styles.heroTitle}>{plan.title}</h1>
            <p className={styles.heroDesc}>{plan.description}</p>

            {/* Quick stats row */}
            <div className={styles.metrics}>
              <span className={styles.metricPill}>
                <Calendar size={15} />
                {totalDays} day plan
              </span>
              <span className={styles.metricPill}>
                <BookOpen size={15} />
                {plan.chapters.length} chapters
              </span>
              <span className={styles.metricPill}>
                <Target size={15} />
                {estimatedQuestions}+ questions
              </span>
              <span className={styles.metricPill}>
                <Zap size={15} />
                {estimatedXp.toLocaleString()} XP to earn
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Two-Column Content Grid ── */}
      <div className={styles.grid}>

        {/* ── LEFT: Chapter / Module List ── */}
        <div className={styles.card}>
          <div className={styles.cardHeader}>
            <h2 className={styles.cardTitle}>
              <BookOpen size={18} color={plan.accent} />
              Learning Modules
            </h2>
            <span className={styles.cardBadge}>{plan.chapters.length} chapters</span>
          </div>

          <ol className={styles.moduleList}>
            {plan.chapters.map((chapter, index) => {
              /*
               * Estimate days per chapter by distributing total days evenly.
               * The first and last chapters get slight adjustments (intro + review).
               */
              const baseDays = Math.round(totalDays / plan.chapters.length);
              const chapterDays = index === 0 ? Math.ceil(baseDays * 1.1) : baseDays;

              return (
                <li key={chapter} className={styles.moduleItem}>
                  {/* Chapter number badge */}
                  <span
                    className={styles.moduleNumber}
                    style={{ background: plan.accent }}
                  >
                    {String(index + 1).padStart(2, "0")}
                  </span>

                  {/* Chapter details */}
                  <div className={styles.moduleContent}>
                    <strong className={styles.moduleName}>{chapter}</strong>
                    <div className={styles.moduleMeta}>
                      <span className={styles.moduleTag}>
                        <Clock size={11} />
                        {chapterDays} days
                      </span>
                      <span className={styles.moduleTag}>
                        <Target size={11} />
                        15 questions
                      </span>
                      {index < 3 && (
                        <span className={styles.moduleTagGreen}>
                          <CheckCircle2 size={11} />
                          Start here
                        </span>
                      )}
                    </div>
                    <small className={styles.moduleHint}>
                      Study each day's topic, solve practice questions, then unlock a chapter quiz.
                    </small>
                  </div>

                  {/* Arrow icon */}
                  <ChevronRight size={16} color="var(--color-text-tertiary)" className={styles.moduleArrow} />
                </li>
              );
            })}
          </ol>
        </div>

        {/* ── RIGHT: Sticky Sidebar ── */}
        <aside className={styles.sidebar}>

          {/* CTA Card */}
          <div className={styles.ctaCard} style={{ borderTopColor: plan.accent }}>
            <div className={styles.ctaIcon} style={{ background: `${plan.accent}1A`, color: plan.accent }}>
              <TrendingUp size={22} />
            </div>
            <h3 className={styles.ctaTitle}>Ready to start?</h3>
            <p className={styles.ctaText}>
              Complete this {totalDays}-day plan to earn {estimatedXp.toLocaleString()} XP
              and unlock Battle mode for this subject.
            </p>

            {/* Stats */}
            <div className={styles.ctaStats}>
              <div className={styles.ctaStat}>
                <span className={styles.ctaStatValue}>{totalDays}</span>
                <span className={styles.ctaStatLabel}>Days</span>
              </div>
              <div className={styles.ctaStatDivider} />
              <div className={styles.ctaStat}>
                <span className={styles.ctaStatValue}>{plan.chapters.length}</span>
                <span className={styles.ctaStatLabel}>Chapters</span>
              </div>
              <div className={styles.ctaStatDivider} />
              <div className={styles.ctaStat}>
                <span className={styles.ctaStatValue}>{estimatedQuestions}+</span>
                <span className={styles.ctaStatLabel}>Questions</span>
              </div>
            </div>

            {/* Start button */}
            <Link href="/sign-up" className={styles.primaryAction} style={{ background: plan.accent }}>
              Start Learning Now
              <ArrowRight size={16} />
            </Link>

            {/* Already have account */}
            <p className={styles.ctaAlready}>
              Already have an account?{" "}
              <Link href="/sign-in" style={{ color: plan.accent }}>Sign in</Link>
            </p>
          </div>

          {/* Features List */}
          <div className={styles.sideCard}>
            <h3 className={styles.sideCardTitle}>What you get</h3>
            <ul className={styles.featureList}>
              {[
                { icon: CheckCircle2, text: "NCERT-aligned chapter-wise questions" },
                { icon: Flame, text: "Daily streak tracking in IST" },
                { icon: Trophy, text: "Battle opponents in this subject" },
                { icon: Star, text: "XP and level-up rewards" },
                { icon: Brain, text: "YouTube hints after wrong answers" },
                { icon: Users, text: "Community discussion per chapter" },
              ].map(({ icon: Icon, text }) => (
                <li key={text} className={styles.featureItem}>
                  <Icon size={15} color="var(--color-success)" />
                  <span>{text}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Study Tips */}
          <div className={styles.sideCard}>
            <h3 className={styles.sideCardTitle}>
              <Brain size={16} style={{ marginRight: 6, verticalAlign: "middle" }} />
              Study Tips
            </h3>
            <ol className={styles.tipList}>
              {studyTips.map((tip, i) => (
                <li key={i} className={styles.tipItem}>
                  <span className={styles.tipNumber}>{i + 1}</span>
                  <span>{tip}</span>
                </li>
              ))}
            </ol>
          </div>

        </aside>
      </div>
    </div>
  );
}
